version: '3'
services:
  zookeeper:
    image: eventuateio/eventuateio-local-zookeeper:0.15.0
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: eventuateio/eventuateio-local-kafka:0.15.0
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
      - KAFKA_HEAP_OPTS=-Xmx192m -Xms192m
      - ZOOKEEPER_SERVERS=zookeeper:2181
  mysql:
    build: ./mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
  tram-cdc-service:
    image: eventuateio/eventuate-tram-cdc-mysql-service:0.4.0.RELEASE
    ports:
      - "8099:8080"
    depends_on:
      - mysql
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_CDC_DB_USER_NAME: root
      EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
      EVENTUATELOCAL_CDC_BINLOG_CLIENT_ID: 1234567890
      EVENTUATELOCAL_CDC_SOURCE_TABLE_NAME: message
  eventuate-local-cdc-service:
    image: eventuateio/eventuateio-local-cdc-service:0.16.2.RELEASE
    ports:
      - "8098:8080"
    depends_on:
      - mysql
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_CDC_DB_USER_NAME: root
      EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
      EVENTUATELOCAL_CDC_LEADERSHIP_LOCK_PATH: /eventuatelocal/cdc/leader1
  ftgo-consumer-service:
    build: ./ftgo-consumer-service
    ports:
      - "8081:8080"
    depends_on:
      - mysql
      - kafka
      - tram-cdc-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/ftgoconsumerservice
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      JAVA_OPTS: -Xmx192m
  ftgo-order-service:
    build: ./ftgo-order-service
    ports:
      - "8082:8080"
    depends_on:
      - mysql
      - kafka
      - tram-cdc-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/ftgoorderservice
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      JAVA_OPTS: -Xmx192m
  ftgo-restaurant-order-service:
      build: ./ftgo-restaurant-order-service
      ports:
        - "8083:8080"
      depends_on:
        - mysql
        - kafka
        - zookeeper
        - tram-cdc-service
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql/ftgorestaurantorderservice
        SPRING_DATASOURCE_USERNAME: mysqluser
        SPRING_DATASOURCE_PASSWORD: mysqlpw
        SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
        EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
        EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
        JAVA_OPTS: -Xmx192m
  ftgo-restaurant-service:
      build: ./ftgo-restaurant-service
      ports:
        - "8084:8080"
      depends_on:
        - mysql
        - kafka
        - zookeeper
        - tram-cdc-service
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql/ftgorestaurantservice
        SPRING_DATASOURCE_USERNAME: mysqluser
        SPRING_DATASOURCE_PASSWORD: mysqlpw
        SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
        EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
        EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
        JAVA_OPTS: -Xmx192m
  ftgo-accounting-service:
        build: ./ftgo-accounting-service
        ports:
          - "8085:8080"
        depends_on:
          - mysql
          - kafka
          - zookeeper
          - eventuate-local-cdc-service
        environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://mysql/ftgoaccountingservice
          SPRING_DATASOURCE_USERNAME: mysqluser
          SPRING_DATASOURCE_PASSWORD: mysqlpw
          SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
          EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
          EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
          JAVA_OPTS: -Xmx192m
  ftgo-order-history-service:
        build: ./ftgo-order-history-service
        ports:
          - "8086:8080"
        depends_on:
          - kafka
          - zookeeper
          - tram-cdc-service
          - dynamodblocal
        environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://mysql/ftgoorderhistoryservice
          SPRING_DATASOURCE_USERNAME: mysqluser
          SPRING_DATASOURCE_PASSWORD: mysqlpw
          SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
          EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
          EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
          AWS_DYNAMODB_ENDPOINT_URL: http://dynamodblocal:8000
          AWS_REGION: $AWS_REGION
          JAVA_OPTS: -Xmx192m
  ftgo-api-gateway:
    build: ./ftgo-api-gateway
    ports:
      - "8087:8080"
    environment:
      ORDER_DESTINATIONS_ORDERSERVICEURL: http://ftgo-order-service:8080
      ORDER_DESTINATIONS_ORDERHISTORYSERVICEURL: http://ftgo-order-history-service:8080
      CONSUMER_DESTINATIONS_CONSUMERSERVICEURL: http://ftgo-consumer-service:8080
      JAVA_OPTS: -Xmx192m

  dynamodblocal:
    build: ./dynamodblocal
    ports:
     - "8000:8000"
    environment:
      JAVA_OPTS: -Xmx128m
