version:               2
jobs:
  build:
    machine:           true
    working_directory: ~/ftgo-application
    steps:
      - checkout
      - restore_cache:
          key:         ftgo-application-{{ checksum "build.gradle" }}
      - run:           TERM=dumb ./build-contracts.sh
      - run:           TERM=dumb ./gradlew testClasses
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key:         ftgo-application-{{ checksum "build.gradle" }}
      - run:
          command:     |
            export TERM=dumb
            . ./setenv-circle-ci.sh
            ./build-and-test-all.sh
      - run:
          name:        Save test results
          command:     |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when:        always
      - store_test_results:
          path:        ~/junit
      - store_artifacts:
          path:        ~/junit
      - run: ./publish-docker-images.sh
